#!/bin/bash
# location of epstool 
ESPPATH=/Users/abn/Library/Arduino15/packages/esp32
# port where EPS32 is connected
PORT=/dev/cu.SLAB_USBtoUART

$ESPPATH/tools/esptool_py/2.6.0/esptool --chip esp32 --port $PORT --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0xe000 boot_app0.bin 0x1000 bootloader_qio_80m.bin 0x10000 MagOD.ino.bin 0x8000 MagOD.ino.partitions.bin
